INCLUDE("${CMAKE_CURRENT_LIST_DIR}/SetUtils.cmake")

TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_CUDA ON)
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_CUDA_LAMBDA ON)
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_SERIAL OFF)
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_CUDA_UVM OFF)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_CUDA ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_CUBLAS ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_CUSOLVER ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_CUSPARSE ON)

#Find the settings that fit your use best
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ARCH_VOLTA70 ON)
