INCLUDE("${CMAKE_CURRENT_LIST_DIR}/SetUtils.cmake")

set(CMAKE_BUILD_TYPE "RELWITHDEBINFO" CACHE STRING "")
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_DEBUG_BOUNDS_CHECK ON)

TRIL_SET_BOOL_CACHE_VAR(HAVE_TEUCHOS_COMM_TIMERS ON)

TRIL_SET_BOOL_CACHE_VAR(Belos_Tpetra_Timers ON)
TRIL_SET_BOOL_CACHE_VAR(Anasazi_Tpetra_Timers ON)
