INCLUDE("${CMAKE_CURRENT_LIST_DIR}/SetUtils.cmake")

TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_HIP ON)
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ENABLE_SERIAL OFF)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_HIP ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_ROCBLAS ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_ROCSOLVER ON)
TRIL_SET_BOOL_CACHE_VAR(TPL_ENABLE_ROCSPARSE ON)

#Find the settings that fit your use best
TRIL_SET_BOOL_CACHE_VAR(Kokkos_ARCH_AMD_GFX942_APU ON)
