INCLUDE("${CMAKE_CURRENT_LIST_DIR}/SetUtils.cmake")

TRIL_SET_BOOL_CACHE_VAR(Trilinos_ENABLE_Tpetra ON)
TRIL_SET_BOOL_CACHE_VAR(Tpetra_ENABLE_TESTS ON)
TRIL_SET_BOOL_CACHE_VAR(Tpetra_ENABLE_EXAMPLES ON)
TRIL_SET_BOOL_CACHE_VAR(Tpetra_INST_SERIAL ON)
